### ISSUE TITLE
[images.txt](https://github.com/DinoMax00/TJ-FPGA_MP3/files/7828568/images.txt)

### ISSUE THREAD

**Issue by qbdl** [DinoMax00/TJ-FPGA_MP3#2]
[images.txt](https://github.com/DinoMax00/TJ-FPGA_MP3/files/7828568/images.txt)
就分别生成多张，然后按顺序粘贴到一个文本里

_Originally posted by @DinoMax00 in https://github.com/DinoMax00/TJ-FPGA_MP3/issues/1#issuecomment-1007345576_

**Comment by qbdl** [comment]
那请问一下，有没有办法单独测oled的模块呢？那个IP核生成的address里面有一个BlueTooth传进去的current，我现在想要让oled测试某一张图片，该如何替代current呢？

**Comment by DinoMax00** [comment]
你把current改成一个定值？这个你自己研究吧，应该不难改。

**Comment by qbdl** [comment]
好的，谢谢，打扰了

**Comment by qbdl** [comment]
不好意思，又来请教一下，您给的images.txt好像里面没有加分号，所以好像不能运行；我按照提示把图片的coe合成，但是用一个定值current，在oled屏幕上仅显示出一条红线，并没有一张图片，可以请教一下吗？非常感谢

**Comment by DinoMax00** [comment]
> 不好意思，又来请教一下，您给的images.txt好像里面没有加分号，所以好像不能运行；我按照提示把图片的coe合成，但是用一个定值current，在oled屏幕上仅显示出一条红线，并没有一张图片，可以请教一下吗？非常感谢

我发的就是我去年用的ip核，后缀名coe改成txt了而已，没分号应该不影响？你在工程项目里把ip核的宽度信息之类的设置对了吗，每一行1536位，oled很多地方都可能出错，包括连线之类的，没遇见过你说的这种错误。

**Comment by qbdl** [comment]
没错了，就是我的宽度设错了
